<Project>
	<PropertyGroup>
		<!-- CSharp Language Version Packages -->
		<LangVersion>14</LangVersion>
		<!-- Current Version Packages -->
		<Version>10.0.1</Version>
		<!-- All Microsoft TargetFrameworks Packages -->
		<MicrosoftTargetFramework>net10.0</MicrosoftTargetFramework>
		<!-- All Abp Version Packages -->
		<AbpVersion>10.1.0-rc.2</AbpVersion>
		<!-- All Abp Theme Version Packages -->
		<AbpLeptonXLiteThemeVersion>4.3.6</AbpLeptonXLiteThemeVersion>
		<!-- All Abp Studio Clien Version Packages -->
		<AbpStudioClientVersion>1.4.1</AbpStudioClientVersion>
        <!-- All Microsoft Version Packages -->
		<MicrosoftVersion>10.0.0</MicrosoftVersion>
	</PropertyGroup>
</Project>