FROM mcr.microsoft.com/dotnet/aspnet:9.0  AS base
COPY bin/Release/net9.0/publish/ app/
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src
RUN dotnet dev-certs https -v -ep openiddict.pfx -p fc3356c0-3ae2-4d9f-b9ad-e60c4a35ed01

FROM base AS final
WORKDIR /app
COPY --from=build /src .

ENTRYPOINT ["dotnet", "Heal.HttpApi.Host.dll"]